// "Hayat planımı kur" akışının metinleri (Aklındakileri dök penceresinden açılır).
// Web ve mobil aynı akışı gösterdiği için ortak pakette; her uygulamanın i18n'i birleştirir.
// tr, en ile aynı anahtarları taşımak zorunda.

export const lifeSetupEn = {
  setup_link: 'Set up my life plan',
  setup_title: 'Set up my life plan',
  setup_hint: 'Describe your routines, goals and how you like your days to run, in your own words. You review everything before anything is saved.',
  setup_placeholder: 'e.g. I work out Mon, Wed, Fri mornings, 42 day program, started 10 days ago. Prayers are not tracked. At most 3 heavy tasks a day. Learn English this quarter.',
  setup_counter: '{n} / {max}',
  setup_extract: 'Build my plan',
  setup_loading: 'Reading your text and drafting a plan',
  setup_back: 'Back',
  setup_review_hint: 'Untick anything you do not want. Nothing is saved until you press Apply.',
  setup_summary_label: 'Summary',
  setup_sec_routines: 'Routines',
  setup_sec_goals: 'Goals',
  setup_sec_tasks: 'Tasks',
  setup_sec_rules: 'Planning rules',
  setup_sec_unsupported: 'Not supported yet',
  setup_unsupported_note: 'These could not be set up by the app and will be skipped.',
  setup_empty: 'No routines, goals, tasks or rules could be found in that text. Add a bit more detail and try again.',
  setup_nothing_selected: 'Nothing selected',

  setup_protected: 'Protected',
  setup_untracked: 'No counter',
  setup_written: 'Saved',
  setup_goal_partial: 'Goal saved, steps pending (retry)',
  setup_program_days: '{n} day program',
  setup_program_start: '{n} already done',
  setup_freq_daily: 'Every day',
  setup_freq_week: '{n} days a week',
  setup_freq_day: '{n} times a day',
  setup_minutes: '{n} min',
  setup_steps: '{n} steps',
  setup_horizon_quarter: 'Quarter',
  setup_horizon_month: 'Month',
  setup_horizon_week: 'Week',
  setup_goal_target: 'Target {n} {unit}',
  setup_area_career: 'Career',
  setup_area_health: 'Health',
  setup_area_personal: 'Personal',
  setup_area_spiritual: 'Spiritual',
  setup_area_social: 'Social',

  setup_rule_max_deep_tasks: 'At most {n} heavy tasks a day',
  setup_rule_rollover_carry: 'Missed tasks carry over to today',
  setup_rule_rollover_backlog: 'Missed tasks go back to the backlog',
  setup_rule_buffer_minutes: '{n} min buffer between blocks',
  setup_rule_about: 'Your own words: {text}',

  setup_apply: 'Apply ({n})',
  setup_apply_rest: 'Apply the rest ({n})',
  setup_applying: 'Saving',

  setup_err_empty: 'Write a few sentences first.',
  setup_err_too_long: 'That text is too long. Shorten it and try again.',
  setup_err_generic: 'The plan could not be drafted. Try again.',
  setup_err_apply: 'Saving stopped halfway. Items marked Saved are in your app, the others are not. Press Apply the rest to continue.',
  setup_err_apply_none: 'Nothing was saved. Check your connection and try again.',
  setup_pro_needed: 'Your free AI allowance is used up. Go Pro to keep building plans.',
}

export const lifeSetupTr: typeof lifeSetupEn = {
  setup_link: 'Hayat planımı kur',
  setup_title: 'Hayat planımı kur',
  setup_hint: 'Rutinlerini, hedeflerini ve günlerinin nasıl işlemesini istediğini kendi cümlelerinle anlat. Hiçbir şey kaydedilmeden önce hepsini gözden geçirirsin.',
  setup_placeholder: 'Örn. Pzt, Çar, Cum sabahları spor yapıyorum, 42 günlük program, 10 gün önce başladım. Namazlar sayaçsız olsun. Günde en çok 3 ağır iş. Bu çeyrekte İngilizce öğren.',
  setup_counter: '{n} / {max}',
  setup_extract: 'Planı çıkar',
  setup_loading: 'Metnin okunuyor ve plan hazırlanıyor',
  setup_back: 'Geri',
  setup_review_hint: 'İstemediklerinin tikini kaldır. Uygula\'ya basana kadar hiçbir şey kaydedilmez.',
  setup_summary_label: 'Özet',
  setup_sec_routines: 'Rutinler',
  setup_sec_goals: 'Hedefler',
  setup_sec_tasks: 'Görevler',
  setup_sec_rules: 'Planlama kuralları',
  setup_sec_unsupported: 'Henüz desteklenmeyenler',
  setup_unsupported_note: 'Bunlar uygulamada kurulamadı ve atlanacak.',
  setup_empty: 'Bu metinde rutin, hedef, görev ya da kural bulunamadı. Biraz daha ayrıntı ekleyip tekrar dene.',
  setup_nothing_selected: 'Hiçbir şey seçili değil',

  setup_protected: 'Korumalı',
  setup_untracked: 'Sayaçsız',
  setup_written: 'Kaydedildi',
  setup_goal_partial: 'Hedef kaydedildi, adımlar bekliyor (tekrar dene)',
  setup_program_days: '{n} günlük program',
  setup_program_start: '{n} günü tamam',
  setup_freq_daily: 'Her gün',
  setup_freq_week: 'Haftada {n} gün',
  setup_freq_day: 'Günde {n} kez',
  setup_minutes: '{n} dk',
  setup_steps: '{n} adım',
  setup_horizon_quarter: 'Çeyrek',
  setup_horizon_month: 'Ay',
  setup_horizon_week: 'Hafta',
  setup_goal_target: 'Hedef {n} {unit}',
  setup_area_career: 'Kariyer',
  setup_area_health: 'Sağlık',
  setup_area_personal: 'Kişisel',
  setup_area_spiritual: 'Maneviyat',
  setup_area_social: 'Sosyal',

  setup_rule_max_deep_tasks: 'Günde en çok {n} ağır iş',
  setup_rule_rollover_carry: 'Kaçan görevler bugüne taşınır',
  setup_rule_rollover_backlog: 'Kaçan görevler birikime döner',
  setup_rule_buffer_minutes: 'Bloklar arası {n} dk tampon',
  setup_rule_about: 'Kendi sözlerin: {text}',

  setup_apply: 'Uygula ({n})',
  setup_apply_rest: 'Kalanları uygula ({n})',
  setup_applying: 'Kaydediliyor',

  setup_err_empty: 'Önce birkaç cümle yaz.',
  setup_err_too_long: 'Metin çok uzun. Kısaltıp tekrar dene.',
  setup_err_generic: 'Plan hazırlanamadı. Tekrar dene.',
  setup_err_apply: 'Kayıt yarıda kaldı. Kaydedildi işaretli öğeler uygulamanda, diğerleri değil. Devam etmek için Kalanları uygula\'ya bas.',
  setup_err_apply_none: 'Hiçbir şey kaydedilmedi. Bağlantını kontrol edip tekrar dene.',
  setup_pro_needed: 'Ücretsiz AI hakkın bitti. Plan çıkarmaya devam etmek için Pro\'ya geç.',
}
