// Task domain types
// Bu dosya Supabase şemasını yansıtır (supabase/migrations/001_core_schema.sql)
// database.ts (generated) ham DB tiplerini içerir; burası uygulama katmanı tipleri

export type TaskStatus = 'backlog' | 'planned' | 'in_progress' | 'blocked' | 'done' | 'deferred'

export interface WsjfScores {
  value_score: number    // 1-5: İş/kullanıcı değeri
  urgency_score: number  // 1-5: Zaman hassasiyeti
  risk_score: number     // 1-5: Risk azaltma / fırsat
  effort_score: number   // 1-5: Tahmini efor
  friction_score: number // 1-5: Yapılmasının önündeki engel
}

export interface ChecklistItem {
  id: string
  text: string
  checked: boolean
}

export interface Attachment {
  id: string
  name: string
  url: string
  type: string // MIME type
}

export interface TaskDetail {
  id: string
  task_id: string
  notes: string | null
  checklist: ChecklistItem[]
  attachments: Attachment[]
  created_at: string
  updated_at: string
}

export interface Task extends WsjfScores {
  id: string
  user_id: string
  parent_task_id: string | null

  title: string
  description: string | null
  status: TaskStatus

  priority_score: number // Generated by DB: (value+urgency+risk)/(effort+friction)

  due_date: string | null      // DATE format: 'YYYY-MM-DD'
  scheduled_date: string | null
  estimated_minutes: number | null
  is_time_blocked: boolean

  is_recurring: boolean
  recurrence_rule: string | null // RRULE format

  tags: string[]
  sort_order: number
  completed_at: string | null
  created_at: string
  updated_at: string

  // Join'lerle gelen (opsiyonel)
  task_details?: TaskDetail
  subtasks?: Task[]
}

export interface TaskFilters {
  status?: TaskStatus | TaskStatus[]
  scheduled_date?: string
  tags?: string[]
  parent_task_id?: string | null
  include_details?: boolean
}

export interface CreateTaskInput {
  title: string
  description?: string
  status?: TaskStatus
  parent_task_id?: string
  due_date?: string
  scheduled_date?: string
  estimated_minutes?: number
  tags?: string[]
  value_score?: number
  urgency_score?: number
  risk_score?: number
  effort_score?: number
  friction_score?: number
}

export type UpdateTaskInput = Partial<Omit<CreateTaskInput, 'title'> & {
  title: string
  status: TaskStatus
  is_time_blocked: boolean
  sort_order: number
  completed_at: string | null
}>
